---
# tasks file for ssh
- name: Remove user ubuntu
  user:
    name: ubuntu
    state: absent
    remove: yes

- name: Create Ansible user 
  user:
    name: raka7
    comment: "Ansible deployment user"
    shell: /bin/bash

- name: Add Ansible user to sudoers file
  copy:
    src: etc/sudoers.d/raka7
    dest: /etc/sudoers.d/raka7
    owner: root
    group: root
    mode: 0220

- name: Add Ansible user's Key
  authorized_key:
    user: raka7
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_raka7.pub') }}"
